/* Generated by tools/build-gallery.py — do not hand-edit. */
const GALLERY = {
 "mustang-600": {
  "name": "Mustang, 2025",
  "spec": "600 stars · full ambient · underglow",
  "clips": [
   [
    "01.mp4",
    720,
    1280
   ]
  ],
  "shots": [
   [
    "01.jpg",
    1050,
    1400
   ],
   [
    "02.jpg",
    787,
    1400
   ],
   [
    "03.jpg",
    787,
    1400
   ],
   [
    "04.jpg",
    787,
    1400
   ]
  ]
 },
 "durango": {
  "name": "Dodge Durango Hornet, 2025",
  "spec": "600 stars · full ambient · footwells",
  "clips": [
   [
    "01.mp4",
    720,
    1280
   ]
  ],
  "shots": [
   [
    "01.jpg",
    787,
    1400
   ],
   [
    "02.jpg",
    1050,
    1400
   ],
   [
    "03.jpg",
    1050,
    1400
   ],
   [
    "04.jpg",
    1050,
    1400
   ],
   [
    "05.jpg",
    1050,
    1400
   ],
   [
    "06.jpg",
    1050,
    1400
   ],
   [
    "07.jpg",
    1050,
    1400
   ],
   [
    "08.jpg",
    1050,
    1400
   ],
   [
    "09.jpg",
    1050,
    1400
   ],
   [
    "10.jpg",
    1050,
    1400
   ],
   [
    "11.jpg",
    1050,
    1400
   ]
  ]
 },
 "mustang-gt": {
  "name": "Mustang GT, 2025",
  "spec": "Full ambient kit · footwells",
  "clips": [
   [
    "01.mp4",
    720,
    1280
   ]
  ],
  "shots": [
   [
    "01.jpg",
    1050,
    1400
   ],
   [
    "02.jpg",
    1050,
    1400
   ],
   [
    "03.jpg",
    1050,
    1400
   ],
   [
    "04.jpg",
    1050,
    1400
   ],
   [
    "05.jpg",
    1050,
    1400
   ],
   [
    "06.jpg",
    1050,
    1400
   ],
   [
    "07.jpg",
    1050,
    1400
   ],
   [
    "08.jpg",
    1050,
    1400
   ]
  ]
 },
 "king-ranch": {
  "name": "Ford F-150 King Ranch",
  "spec": "800 stars · full ambient · footwells · panoramic roof",
  "clips": [
   [
    "01.mp4",
    720,
    1280
   ],
   [
    "02.mp4",
    720,
    1280
   ]
  ],
  "shots": [
   [
    "01.jpg",
    919,
    1400
   ],
   [
    "02.jpg",
    1050,
    1400
   ],
   [
    "03.jpg",
    1050,
    1400
   ],
   [
    "04.jpg",
    1050,
    1400
   ],
   [
    "05.jpg",
    1050,
    1400
   ]
  ]
 },
 "audi-a4": {
  "name": "Audi A4, 2019",
  "spec": "600 stars · full ambient · footwells",
  "clips": [
   [
    "01.mp4",
    720,
    1280
   ],
   [
    "02.mp4",
    720,
    1280
   ]
  ],
  "shots": [
   [
    "01.jpg",
    781,
    1400
   ],
   [
    "02.jpg",
    1050,
    1400
   ],
   [
    "03.jpg",
    1050,
    1400
   ],
   [
    "04.jpg",
    1050,
    1400
   ],
   [
    "05.jpg",
    1050,
    1400
   ],
   [
    "06.jpg",
    1050,
    1400
   ]
  ]
 },
 "rx7": {
  "name": "Mazda RX-7",
  "spec": "Rainbow underglow, wheel to wheel",
  "clips": [
   [
    "01.mp4",
    720,
    1280
   ],
   [
    "02.mp4",
    720,
    1280
   ]
  ],
  "shots": [
   [
    "01.jpg",
    1050,
    1400
   ]
  ]
 },
 "sierra": {
  "name": "GMC Sierra, 2023",
  "spec": "8-strip ambient · sunroof · footwells",
  "clips": [
   [
    "01.mp4",
    720,
    1280
   ]
  ],
  "shots": [
   [
    "01.jpg",
    1050,
    1400
   ],
   [
    "02.jpg",
    1050,
    1400
   ],
   [
    "03.jpg",
    1050,
    1400
   ],
   [
    "04.jpg",
    1050,
    1400
   ],
   [
    "05.jpg",
    1050,
    1400
   ],
   [
    "06.jpg",
    1050,
    1400
   ],
   [
    "07.jpg",
    1050,
    1400
   ]
  ]
 }
};
